
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
  group-configs:
    - group: default
      paths-to-match: /**

knife4j:
  enable: true
  setting:
    language: zh_cn
    enable-footer: false
    enable-version: true
    enable-dynamic-parameter: true
