server:
  port: 8080
  servlet:
    encoding:
      charset: utf-8

spring:
  profiles:
    active:
      - logging
      - mybatis-plus
      - springdoc
      - connect
  application:
    name: server
  web:
    locale: zh_CN
    locale-resolver: fixed
    resources:
      static-locations:
        - file:./front/dist
      chain:
        enabled: true
        cache: true
        compressed: false
        strategy:
          content:
            enabled: false
      cache:
        cachecontrol:
          cache-public: true
          max-age: P30D
          s-max-age: P30D
  messages:
    encoding: UTF-8
  main:
    banner-mode: off
  output:
    ansi:
      enabled: always
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  jackson:
    default-property-inclusion: non_null
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      write-bigdecimal-as-plain: true
      write-dates-as-timestamps: false
    deserialization:
      adjust-dates-to-context-time-zone: false
  task:
    execution:
      thread-name-prefix: Exec-
      pool:
        allow-core-thread-timeout: true
        core-size: 4
        keep-alive: 60s
        max-size: 16
        queue-capacity: 64
    scheduling:
      pool.size: 3
      thread-name-prefix: Task-
